name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  pest:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.4

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Run Test
        run: vendor/bin/pest
